DELETE FROM expenses;
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-21', 697, 'Transportation', 'Train tickets');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-14', 630, 'Miscellaneous', 'Stationery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-07', 1414, 'Groceries', 'Monthly grocery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-06', 730, 'Miscellaneous', 'Donation');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-21', 639, 'Miscellaneous', 'Pet supplies');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-11', 1258, 'Groceries', 'Bought vegetables');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-30', 3731, 'Shopping', 'Accessories');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-06', 1810, 'Shopping', 'Online shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-15', 140, 'Miscellaneous', 'Home maintenance');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-03', 501, 'Entertainment', 'Streaming service');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-04', 1933, 'Entertainment', 'Dining out');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-29', 3089, 'Healthcare', 'Medicines');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-13', 1409, 'Miscellaneous', 'Donation');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-05', 2998, 'Education', 'Exam fee');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-11', 2221, 'Shopping', 'Footwear purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-28', 318, 'Miscellaneous', 'Stationery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-15', 1113, 'Miscellaneous', 'Donation');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-17', 184, 'Entertainment', 'Amusement park');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-29', 767, 'Transportation', 'Train tickets');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-23', 3009, 'Healthcare', 'Medicines');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-07', 2105, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-10', 416, 'Groceries', 'Dairy products');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-08', 312, 'Groceries', 'Monthly grocery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-29', 612, 'Transportation', 'Fuel');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-18', 1850, 'Utilities', 'Internet bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-29', 6439, 'Education', 'Stationery items');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-10', 1269, 'Groceries', 'Snacks and essentials');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-11', 2809, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-30', 824, 'Utilities', 'Mobile recharge');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-15', 2470, 'Utilities', 'Gas bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-21', 2678, 'Healthcare', 'Health checkup');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-13', 1068, 'Miscellaneous', 'Pet supplies');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-02', 756, 'Utilities', 'Electricity bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-10', 3039, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-13', 510, 'Shopping', 'Clothes shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-08', 2140, 'Entertainment', 'Concert');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-31', 336, 'Transportation', 'Taxi ride');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-15', 1117, 'Healthcare', 'Lab tests');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-30', 403, 'Transportation', 'Train tickets');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-28', 143, 'Transportation', 'Taxi ride');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-02', 3074, 'Education', 'Books purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-30', 2299, 'Entertainment', 'Streaming service');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-16', 100, 'Healthcare', 'Medicines');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-21', 1117, 'Groceries', 'Dairy products');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-12', 204, 'Groceries', 'Supermarket purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-02', 3761, 'Shopping', 'Footwear purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-28', 2984, 'Shopping', 'Accessories');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-02', 1163, 'Healthcare', 'Dental care');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-10', 1941, 'Groceries', 'Dairy products');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-28', 831, 'Miscellaneous', 'Laundry');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-31', 1192, 'Healthcare', 'Lab tests');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-23', 1890, 'Groceries', 'Bought vegetables');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-06', 305, 'Transportation', 'Train tickets');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-26', 1138, 'Utilities', 'Water bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-22', 2170, 'Entertainment', 'Amusement park');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-29', 1797, 'Groceries', 'Bought vegetables');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-03', 1677, 'Healthcare', 'Doctor visit');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-12', 1002, 'Shopping', 'Footwear purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-31', 485, 'Groceries', 'Monthly grocery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-31', 2452, 'Shopping', 'Online shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-17', 1789, 'Groceries', 'Dairy products');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-18', 1673, 'Shopping', 'Clothes shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-13', 123, 'Miscellaneous', 'Home maintenance');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-08', 267, 'Transportation', 'Fuel');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-25', 2250, 'Healthcare', 'Doctor visit');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-16', 442, 'Entertainment', 'Concert');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-12', 1588, 'Healthcare', 'Doctor visit');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-27', 1724, 'Entertainment', 'Streaming service');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-15', 3489, 'Shopping', 'Accessories');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-30', 638, 'Miscellaneous', 'Home maintenance');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-04', 900, 'Miscellaneous', 'Pet supplies');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-12', 148, 'Miscellaneous', 'Stationery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-17', 784, 'Healthcare', 'Lab tests');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-17', 1197, 'Entertainment', 'Streaming service');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-14', 750, 'Utilities', 'Internet bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-01', 1957, 'Entertainment', 'Dining out');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-27', 377, 'Groceries', 'Monthly grocery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-27', 3978, 'Shopping', 'Online shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-24', 1734, 'Utilities', 'Electricity bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-18', 2993, 'Shopping', 'Clothes shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-20', 1147, 'Education', 'Books purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-28', 1913, 'Shopping', 'Footwear purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-03', 766, 'Healthcare', 'Medicines');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-19', 366, 'Healthcare', 'Doctor visit');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-06', 797, 'Groceries', 'Supermarket purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-31', 4985, 'Healthcare', 'Medicines');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-20', 4751, 'Healthcare', 'Lab tests');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-16', 8379, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-31', 2447, 'Shopping', 'Accessories');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-05', 684, 'Transportation', 'Bus fare');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-04', 862, 'Entertainment', 'Amusement park');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-20', 415, 'Transportation', 'Bus fare');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-28', 4488, 'Healthcare', 'Doctor visit');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-22', 1829, 'Groceries', 'Bought vegetables');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-26', 2463, 'Utilities', 'Gas bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-20', 7382, 'Education', 'Course fee');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-29', 3102, 'Shopping', 'Online shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-13', 830, 'Shopping', 'Online shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-25', 9147, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-08', 1838, 'Groceries', 'Monthly grocery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-25', 2706, 'Healthcare', 'Lab tests');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-25', 395, 'Entertainment', 'Amusement park');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-15', 1963, 'Healthcare', 'Dental care');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-03', 684, 'Transportation', 'Taxi ride');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-11', 2447, 'Education', 'Course fee');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-04', 2295, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-22', 3053, 'Shopping', 'Online shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-08', 1842, 'Entertainment', 'Dining out');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-14', 3504, 'Shopping', 'Online shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-05', 2744, 'Shopping', 'Accessories');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-13', 2388, 'Entertainment', 'Amusement park');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-22', 1761, 'Entertainment', 'Concert');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-17', 8340, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-15', 2044, 'Education', 'Exam fee');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-09', 376, 'Miscellaneous', 'Pet supplies');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-15', 7537, 'Education', 'Books purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-16', 1942, 'Entertainment', 'Dining out');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-23', 1219, 'Healthcare', 'Doctor visit');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-16', 2689, 'Utilities', 'Electricity bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-03', 8291, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-16', 2987, 'Shopping', 'Gift items');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-08', 574, 'Miscellaneous', 'Home maintenance');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-01', 1637, 'Utilities', 'Gas bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-03', 363, 'Entertainment', 'Movie tickets');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-21', 546, 'Transportation', 'Auto fare');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-05', 441, 'Entertainment', 'Dining out');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-20', 709, 'Transportation', 'Fuel');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-11', 1199, 'Groceries', 'Dairy products');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-06', 4849, 'Education', 'Exam fee');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-09', 508, 'Groceries', 'Snacks and essentials');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-10', 1524, 'Entertainment', 'Movie tickets');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-10', 1139, 'Shopping', 'Online shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-23', 3685, 'Healthcare', 'Medicines');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-31', 4151, 'Healthcare', 'Medicines');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-28', 2363, 'Entertainment', 'Movie tickets');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-25', 1029, 'Entertainment', 'Streaming service');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-08', 8763, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-09', 2216, 'Utilities', 'Mobile recharge');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-15', 554, 'Groceries', 'Supermarket purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-19', 8254, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-26', 1137, 'Miscellaneous', 'Laundry');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-31', 4560, 'Education', 'Books purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-03', 1001, 'Entertainment', 'Movie tickets');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-21', 234, 'Transportation', 'Taxi ride');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-31', 2837, 'Utilities', 'Electricity bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-01', 418, 'Miscellaneous', 'Home maintenance');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-05', 6594, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-28', 1536, 'Groceries', 'Monthly grocery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-10', 501, 'Healthcare', 'Medicines');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-09', 8473, 'Education', 'Exam fee');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-27', 182, 'Transportation', 'Taxi ride');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-07', 2383, 'Entertainment', 'Dining out');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-17', 127, 'Transportation', 'Fuel');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-26', 1108, 'Groceries', 'Monthly grocery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-12', 2966, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-20', 1545, 'Utilities', 'Gas bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-22', 345, 'Groceries', 'Monthly grocery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-20', 886, 'Groceries', 'Bought vegetables');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-18', 869, 'Entertainment', 'Amusement park');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-14', 2440, 'Utilities', 'Gas bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-28', 3335, 'Shopping', 'Gift items');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-03', 1760, 'Groceries', 'Bought vegetables');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-15', 397, 'Transportation', 'Auto fare');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-15', 990, 'Entertainment', 'Movie tickets');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-04', 1821, 'Entertainment', 'Amusement park');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-31', 2705, 'Utilities', 'Gas bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-18', 699, 'Groceries', 'Snacks and essentials');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-15', 3067, 'Shopping', 'Clothes shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-25', 1778, 'Entertainment', 'Movie tickets');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-23', 688, 'Miscellaneous', 'Stationery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-14', 332, 'Transportation', 'Bus fare');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-28', 8267, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-17', 389, 'Transportation', 'Taxi ride');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-15', 2239, 'Entertainment', 'Amusement park');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-08', 9593, 'Education', 'Books purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-07', 1706, 'Groceries', 'Supermarket purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-17', 949, 'Groceries', 'Monthly grocery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-03', 1628, 'Groceries', 'Snacks and essentials');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-20', 398, 'Transportation', 'Taxi ride');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-27', 2776, 'Healthcare', 'Lab tests');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-09', 4808, 'Healthcare', 'Lab tests');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-16', 4532, 'Education', 'Books purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-17', 433, 'Transportation', 'Taxi ride');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-04', 1516, 'Shopping', 'Clothes shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-05', 7145, 'Education', 'Stationery items');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-31', 468, 'Transportation', 'Fuel');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-21', 1399, 'Education', 'Exam fee');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-27', 377, 'Groceries', 'Supermarket purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-30', 1272, 'Miscellaneous', 'Stationery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-23', 897, 'Utilities', 'Mobile recharge');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-04', 4184, 'Education', 'Course fee');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-16', 1543, 'Groceries', 'Dairy products');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-24', 1110, 'Groceries', 'Dairy products');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-02', 749, 'Transportation', 'Fuel');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-26', 1374, 'Shopping', 'Clothes shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-28', 1472, 'Groceries', 'Supermarket purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-18', 2286, 'Utilities', 'Gas bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-30', 1076, 'Shopping', 'Clothes shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-03', 166, 'Transportation', 'Auto fare');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-23', 1393, 'Groceries', 'Dairy products');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-13', 205, 'Transportation', 'Bus fare');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-13', 392, 'Groceries', 'Supermarket purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-24', 558, 'Transportation', 'Taxi ride');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-18', 2811, 'Healthcare', 'Dental care');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-19', 2113, 'Entertainment', 'Dining out');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-08', 352, 'Transportation', 'Auto fare');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-14', 1790, 'Groceries', 'Supermarket purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-18', 8712, 'Education', 'Books purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-28', 353, 'Transportation', 'Bus fare');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-01', 425, 'Groceries', 'Monthly grocery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-24', 115, 'Miscellaneous', 'Laundry');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-06', 2064, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-13', 917, 'Entertainment', 'Dining out');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-31', 2337, 'Shopping', 'Online shopping');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-22', 235, 'Miscellaneous', 'Laundry');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-13', 984, 'Groceries', 'Dairy products');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-27', 954, 'Groceries', 'Dairy products');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-09', 772, 'Transportation', 'Fuel');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-03', 1428, 'Miscellaneous', 'Pet supplies');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-21', 1090, 'Entertainment', 'Dining out');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-25', 125, 'Miscellaneous', 'Laundry');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-19', 2928, 'Healthcare', 'Health checkup');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-18', 612, 'Transportation', 'Train tickets');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-17', 309, 'Entertainment', 'Concert');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-22', 1365, 'Healthcare', 'Lab tests');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-13', 1623, 'Groceries', 'Monthly grocery');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-05-16', 565, 'Miscellaneous', 'Laundry');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-06-15', 1610, 'Utilities', 'Internet bill');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-23', 9669, 'Education', 'Stationery items');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-03-10', 340, 'Transportation', 'Auto fare');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-10', 6809, 'Education', 'Online class subscription');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-11', 1300, 'Entertainment', 'Streaming service');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-16', 236, 'Miscellaneous', 'Laundry');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-04-15', 671, 'Transportation', 'Taxi ride');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-01-18', 1781, 'Groceries', 'Supermarket purchase');
INSERT INTO expenses (expense_date, amount, category, notes) VALUES ('2025-02-18', 602, 'Groceries', 'Supermarket purchase');